---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.x.x
    AVD_FABRIC:
      children:
        SF_SITE_103:
          children:
            BORDER_LEAFS_103:
              hosts:
                SF_SITE_103_BL-1:
                  ansible_host: 10.255.x.x
            TOR_SITE_103:
              hosts:
                SF_SITE_102_TOR-1A:
                  ansible_host: 10.255.x.x
