---
# L3 interface to TOR

custom_structured_configuration_ethernet_interfaces:
  - name: Ethernet1
    description: Uplink to SF_SITE_102_TOR-1A_HSVPN
    type: routed
    ip_address: 10.255.102.21/31
    encapsulation_dot1q_vlan: 302

# BGP peering with border leaf

custom_structured_configuration_router_bgp:
  as: 65582
  router_id: 10.255.102.21
  redistribute_routes:
    - source_protocol: connected
    # - source_protocol: static
  neighbors:
    - ip_address: 10.255.102.20
      remote_as: '6.6971'
      bfd: true
      peer_group: CE-PEER-GROUP-HSVPN
  address_family_ipv4:
    peer_groups:
      - name: CE-PEER-GROUP-HSVPN
        activate: true
  

# Interface Loopback0 for CE
custom_structured_configuration_loopback_interfaces:
  - name: Loopback0
    description: " CE IP for test for A2AVPN"
    shutdown: false
    ip_address: 10.201.201.2/32

# Static route for BRANCH-HS-CE1 Loopback0 via Hub, SF-SITE-103-BL1
custom_structured_configuration_static_routes:
  - vrf: default
    destination_address_prefix: 10.201.201.1/32
    gateway: 10.255.102.20

# Set TTL value for PTP packets

# custom_structured_configuration_ptp:
#   ttl: 128


