---
# L3 interface to TOR

custom_structured_configuration_ethernet_interfaces:
  - name: Ethernet1
    description: Uplink to SF_SITE_101_TOR-1A_A2AVPN
    type: routed
    ip_address: 10.255.101.1/31
    encapsulation_dot1q_vlan: 100

# BGP peering with border leaf

custom_structured_configuration_router_bgp:
  as: 65501
  router_id: 10.255.101.1
  redistribute_routes:
    - source_protocol: connected
  neighbors:
    - ip_address: 10.255.101.0
      remote_as: '6.6971'
      bfd: true
      peer_group: CE-PEER-GROUP-A2AVPN
  address_family_ipv4:
    peer_groups:
      - name: CE-PEER-GROUP-A2AVPN
        activate: true
  

# Interface Loopback0 for CE
custom_structured_configuration_loopback_interfaces:
  - name: Loopback0
    description: " CE IP for test for A2AVPN"
    shutdown: false
    ip_address: 10.101.101.1/32
