hostname: BRANCH-A2A
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: default
- ip_address: 8.8.4.4
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$ZSpmKHG8tfWO/BQg$qMy2VGDhmykJ.VDcO5LiW9B6pf0TS7zVe4jLwaCiIjxNwBEOXodwhsIwFUD3UuLAR.aDtVZh3DIuSr5X12dmB0
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.28/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
ethernet_interfaces:
- name: Ethernet1
  description: Uplink to SF_SITE_101_TOR-1A
  type: routed
  ip_address: 10.255.101.1/31
- name: Ethernet2
  description: Uplink to SF_SITE_101_TOR-1B
  type: routed
  ip_address: 10.255.101.3/31
router_bgp:
  as: '65501'
  router_id: 10.255.101.1
  neighbors:
  - ip_address: 10.255.101.0
    remote_as: '65000'
    peer_group: CE-PEER-GROUP
  - ip_address: 10.255.101.2
    remote_as: '65000'
    peer_group: CE-PEER-GROUP
  address_family_ipv4:
    peer_groups:
    - name: CE-PEER-GROUP
      activate: true
