hostname: BRANCH-HS-CE1
service_routing_protocols_model: multi-agent
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: default
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 10.255.0.2
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$ZGX/X07MoiWP9hvX$3UaAtOAiBGc54DYHdQt5dsr5P2HLydxjrda51Zw69tSsF4tahXPVj26PwOiZUy/xFRZL3CAkT7.lsOPqWfIbU0
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$gkwcSSEqrAAJh5dy$Svp08.OM0HRY59ALSFdsHWmTkFzBPIHEZpbh3BPFNMFrRosiJCbjsgvr2.M.bDG5LUmuzoaiRUavZeYgtK.wC/
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.42/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
loopback_interfaces:
- name: Loopback0
  description: ' CE IP for test for A2AVPN'
  shutdown: false
  ip_address: 10.201.201.1/32
ip_routing: true
ethernet_interfaces:
- name: Ethernet1
  description: Uplink to SF_SITE_101_TOR-1A_HSVPN
  type: routed
  ip_address: 10.255.101.21/31
  encapsulation_dot1q_vlan: 301
router_bgp:
  as: '65581'
  router_id: 10.255.101.21
  redistribute_routes:
  - source_protocol: connected
  neighbors:
  - ip_address: 10.255.101.20
    remote_as: '6.6971'
    bfd: true
    peer_group: CE-PEER-GROUP-HSVPN
  address_family_ipv4:
    peer_groups:
    - name: CE-PEER-GROUP-HSVPN
      activate: true
static_routes:
- vrf: default
  destination_address_prefix: 10.201.201.2/32
  gateway: 10.255.101.20
