hostname: BRANCH-A2A-CE3
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 10.255.0.2
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$vNCepJnitlh6c6hQ$ucadLuLEnmfS/Wo9047421qz/bC9qclksdQN4nZAqSiPRW.N6WPH3CiR3lkSDGFzU.li94STOj9sWWmL1m9GZ1
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.32/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
loopback_interfaces:
- name: Loopback0
  description: ' CE IP for test'
  shutdown: false
  ip_address: 10.102.102.1/32
- name: Loopback10
  escription: ' CE IP for test for HSVPN'
  shutdown: false
  ip_address: 10.120.120.2/32
  vrf: HSVPN-BRANCH20102
ip_routing: true
ethernet_interfaces:
- name: Ethernet1.102
  description: Uplink to SF_SITE_102_TOR-1A
  type: routed
  ip_address: 10.255.102.1/31
- name: Ethernet1.600
  description: Uplink to SF_SITE_102_TOR-1A_HSVPN
  type: routed
  ip_address: 10.255.102.21/31
  encapsulation_dot1q_vlan: 600
  vrf: HSVPN-BRANCH20102
router_bgp:
  as: '65503'
  router_id: 10.255.102.1
  redistribute_routes:
  - source_protocol: connected
  neighbors:
  - ip_address: 10.255.102.0
    remote_as: '6.6971'
    bfd: true
    peer_group: CE-PEER-GROUP
  address_family_ipv4:
    peer_groups:
    - name: CE-PEER-GROUP
      activate: true
  vrfs:
  - name: HSVPN-BRANCH20102
    router_id: 10.255.102.21
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      bgp: null
      neighbors:
      - ip_address: 10.255.102.20
        activate: true
    neighbors:
    - ip_address: 10.255.102.20
      remote_as: '6.6971'
      bfd: true
      peer_group: CE-PEER-GROUP-HSVPN
vlans:
- id: 102
  name: VLAN_100_A2AVPN
  state: active
- id: 600
  name: VLAN_600_HSVPN
  state: active
