hostname: CORP-A2A-CE2
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: default
- ip_address: 8.8.4.4
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$ZSpmKHG8tfWO/BQg$qMy2VGDhmykJ.VDcO5LiW9B6pf0TS7zVe4jLwaCiIjxNwBEOXodwhsIwFUD3UuLAR.aDtVZh3DIuSr5X12dmB0
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.31/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ip_igmp_snooping:
  globally_enabled: true
router_isis:
  instance: CORE
  address_family_ipv4:
    enabled: true
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2
  address_family_ipv6:
    enabled: true
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2
mac_security:
  fips_restrictions: true
  profiles:
  - name: Backbone
    cipher: aes256-gcm-xpn
    connection_keys:
    - id: 4261636b62306e65
      encrypted_key: 08751E18584F5641105D5E577A7D217E6661204054415A
    mka:
      session:
        rekey_period: 86400
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
loopback_interfaces:
- name: Loopback10
  description: Inband management
  ip_address: 192.168.101.31/32
ethernet_interfaces:
- name: Ethernet1
  description: Uplink to SF_SITE_101_TOR-1B
  type: routed
  ip_address: 10.255.101.7/31
router_bgp:
  as: '65504'
  router_id: 10.255.101.7
  neighbors:
  - ip_address: 10.255.101.6
    remote_as: '6.6971'
    peer_group: CE-PEER-GROUP
  address_family_ipv4:
    peer_groups:
    - name: CE-PEER-GROUP
      activate: true
