hostname: SF-SITE-102-TOR-1A
service_routing_protocols_model: multi-agent
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvvrf: default
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 10.255.0.2
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$ZGX/X07MoiWP9hvX$3UaAtOAiBGc54DYHdQt5dsr5P2HLydxjrda51Zw69tSsF4tahXPVj26PwOiZUy/xFRZL3CAkT7.lsOPqWfIbU0
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$gkwcSSEqrAAJh5dy$Svp08.OM0HRY59ALSFdsHWmTkFzBPIHEZpbh3BPFNMFrRosiJCbjsgvr2.M.bDG5LUmuzoaiRUavZeYgtK.wC/
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.23/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ethernet_interfaces:
- name: Ethernet3
  peer: SF-SITE-102-BL-1
  peer_interface: Ethernet11
  peer_type: pe
  description: SF-SITE-102-BL-1_Ethernet11
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: SF-SITE-102-BL-1
  peer_interface: Ethernet12
  peer_type: pe
  description: SF-SITE-102-BL-1_Ethernet12
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 3
    mode: active
- name: Ethernet7
  peer: BRANCH-A2A-CE3
  peer_interface: Ethernet1
  peer_type: cpe
  description: BRANCH-A2A-CE3_Ethernet1
  shutdown: false
  type: switched
  mode: access
  vlans: '102'
- name: Ethernet8
  peer: CORP-A2A-CE3
  peer_interface: Ethernet1
  peer_type: cpe
  description: CORP-A2A-CE3_Ethernet1
  shutdown: false
  type: switched
  mode: access
  vlans: '202'
- name: Ethernet9
  peer: BRANCH-HS-CE2
  peer_interface: Ethernet1
  peer_type: cpe
  description: BRANCH-HS-CE2_Ethernet1
  shutdown: false
  type: switched
  mode: access
  vlans: '302'
port_channel_interfaces:
- name: Port-Channel3
  description: SF-SITE-102-BL-1_Po11
  type: switched
  shutdown: false
  mode: trunk
  vlans: 102-103,202-203,302
vlans:
- id: 102
  name: vlan_102
  tenant: BRANCH
- id: 103
  name: vlan_103
  tenant: BRANCH
- id: 302
  name: vlan_302
  tenant: BRANCH
- id: 202
  name: vlan_202
  tenant: CORP
- id: 203
  name: vlan_203
  tenant: CORP
ip_igmp_snooping:
  globally_enabled: true
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
loopback_interfaces:
- name: Loopback10
  description: Inband management
  ip_address: 192.168.101.23/32
