hostname: SF-SITE-102-BL-1
router_bgp:
  as: '6.6971'
  router_id: 100.2.2.21
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  bgp_defaults:
  - bgp asn notation asdot
  - bgp always-compare-med
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  graceful_restart:
    enabled: true
    restart_time: 300
  peer_groups:
  - name: MPLS-OVERLAY-PEERS
    type: mpls
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '6.6971'
  address_family_ipv4:
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: false
  address_family_evpn:
    neighbor_default:
      encapsulation: mpls
      next_hop_self_source_interface: Loopback0
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv4:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: null
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv6:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: null
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  neighbors:
  - ip_address: 100.1.1.13
    peer_group: MPLS-OVERLAY-PEERS
    description: SF-SITE-101-RR-1
  - ip_address: 100.1.1.20
    peer_group: MPLS-OVERLAY-PEERS
    description: SF-SITE-102-RR-1
  vrfs:
  - name: BRANCH-10015
    router_id: 100.2.2.21
    rd: 100.2.2.21:10011
    route_targets:
      import:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10011
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10011
      export:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10011
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10011
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      neighbors:
      - ip_address: 10.255.102.1
        activate: true
      bgp:
        additional_paths:
          install: true
    neighbors:
    - ip_address: 10.255.102.1
      remote_as: '65503'
      bfd: true
    eos_cli: 'bgp additional-paths receive

      bgp additional-paths send any

      bgp bestpath tie-break router-id

      '
  - name: CORP-10016
    router_id: 100.2.2.21
    rd: 100.2.2.21:10012
    route_targets:
      import:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10012
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10012
      export:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10012
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10012
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      neighbors:
      - ip_address: 10.255.102.5
        activate: true
      bgp:
        additional_paths:
          install: true
    neighbors:
    - ip_address: 10.255.102.5
      remote_as: '65523'
      bfd: true
    eos_cli: 'bgp additional-paths receive

      bgp additional-paths send any

      bgp bestpath tie-break router-id

      '
  vpws:
  - name: BRANCH
    rd: 100.2.2.21:5000
    route_targets:
      import_export: 6.6971:5000
    pseudowires:
    - name: SF_SITE_101_BL-1-SF_SITE_102_BL-1_99
      id_local: 101
      id_remote: 100
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 10.255.0.2
  vrf: default
local_users:
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$vNCepJnitlh6c6hQ$ucadLuLEnmfS/Wo9047421qz/bC9qclksdQN4nZAqSiPRW.N6WPH3CiR3lkSDGFzU.li94STOj9sWWmL1m9GZ1
vrfs:
- name: default
  ip_routing: false
- name: BRANCH-10015
  tenant: BRANCH
  ip_routing: true
- name: CORP-10016
  tenant: CORP
  ip_routing: true
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.21/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
eos_cli: "!\nmpls label range static 16 15984\nmpls label range bgp-sr 16000 8000\nmpls label range isis-sr 16000 8000\n\n!\nrouter
  bgp 6.6971\n  vpws BRANCH\n    mpls control-word\n  address-family vpn-ipv4\n    bgp additional-paths receive\n    bgp additional-paths
  send any\n  address-family vpn-ipv6\n    bgp additional-paths receive\n    bgp additional-paths send any\n\n!\nrouter isis CORE\n
  \ lsp purge origination-identification\n  set-overload-bit on-startup wait-for-bgp\n  authentication mode md5\n  graceful-restart
  restart-hold-time 300\n  authentication key edwardjones\n  address-family ipv4 unicast\n    bfd all-interfaces\n  address-family ipv6
  unicast\n    bfd all-interfaces\n    multi-topology\ninterface Loopback0\n  isis multi-topology address-family ipv4 unicast\n  isis
  multi-topology address-family ipv6 unicast\n"
ethernet_interfaces:
- name: Ethernet11
  peer: SF-SITE-102-TOR-1A
  peer_interface: Ethernet3
  peer_type: ethernet_aggregation
  description: SF-SITE-102-TOR-1A_Ethernet3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 11
    mode: active
- name: Ethernet12
  peer: SF-SITE-102-TOR-1A
  peer_interface: Ethernet4
  peer_type: ethernet_aggregation
  description: SF-SITE-102-TOR-1A_Ethernet4
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 11
    mode: active
- name: Ethernet3
  peer: SF-SITE-104-BL-1
  peer_interface: Ethernet6
  peer_type: pe
  description: P2P_LINK_TO_SF-SITE-104-BL-1_Ethernet6
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.7/31
  isis_enable: CORE
  isis_metric: 10
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet4
  peer: SF-SITE-102-SPINE-2
  peer_interface: Ethernet3
  peer_type: p
  description: P2P_LINK_TO_SF-SITE-102-SPINE-2_Ethernet3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.5/31
  isis_enable: CORE
  isis_metric: 10
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet7
  peer: SF-SITE-102-RR-1
  peer_interface: Ethernet3
  peer_type: rr
  description: P2P_LINK_TO_SF-SITE-102-RR-1_Ethernet3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.8/31
  isis_enable: CORE
  isis_metric: 10
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet9
  peer: SF-SITE-101-BL-1
  peer_interface: Ethernet9
  peer_type: pe
  description: P2P_LINK_TO_SF-SITE-101-BL-1_Ethernet9
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.3/31
  isis_enable: CORE
  isis_metric: 10
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Port-channel11.102
  peer_type: l3_interface
  ip_address: 10.255.102.0/31
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 102
  vrf: BRANCH-10015
- name: Port-channel11.202
  peer_type: l3_interface
  ip_address: 10.255.102.4/31
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 202
  vrf: CORP-10016
- name: Port-channel11.99
  type: l2dot1q
  peer_type: point_to_point_service
  encapsulation_vlan:
    client:
      dot1q:
        vlan: 99
    network:
      client: true
  shutdown: false
- name: Port-channel11
  type: routed
  peer_type: l3_interface
  shutdown: false
port_channel_interfaces:
- name: Port-Channel11
  description: SF-SITE-102-TOR-1A_Po3
  type: switched
  shutdown: false
  mode: trunk
  vlans: 102-103,202-203
loopback_interfaces:
- name: Loopback0
  description: MPLS_Overlay_peering
  shutdown: false
  ip_address: 100.2.2.21/32
  isis_enable: CORE
  isis_passive: true
  node_segment:
    ipv4_index: 21
- name: Loopback10
  description: Inband management
  ip_address: 192.168.101.21/32
router_isis:
  instance: CORE
  log_adjacency_changes: true
  net: 51.0001.1921.6800.0021.00
  router_id: 100.2.2.21
  is_type: level-2
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2
  timers:
    local_convergence:
      delay: 10000
      protected_prefixes: true
  advertise:
    passive_only: false
  segment_routing_mpls:
    router_id: 100.2.2.21
    enabled: true
  address_family_ipv6:
    enabled: true
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2
mpls:
  ip: true
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
patch_panel:
  patches:
  - name: SF_SITE_101_BL-1-SF_SITE_102_BL-1_99
    enabled: true
    connectors:
    - id: '1'
      type: interface
      endpoint: Port-channel11.99
    - id: '2'
      type: pseudowire
      endpoint: bgp vpws BRANCH pseudowire SF_SITE_101_BL-1-SF_SITE_102_BL-1_99
vlans:
- id: 102
  name: vlan_102
  tenant: BRANCH
- id: 103
  name: vlan_103
  tenant: BRANCH
- id: 202
  name: vlan_202
  tenant: CORP
- id: 203
  name: vlan_203
  tenant: CORP
ip_igmp_snooping:
  globally_enabled: true
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
