hostname: SF_SITE_101_BL-2
router_bgp:
  as: '6.6971'
  router_id: 100.1.2.2
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  bgp_defaults:
  - bgp asn notation asdot
  - bgp always-compare-med
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  graceful_restart:
    enabled: true
    restart_time: 300
  peer_groups:
  - name: MPLS-OVERLAY-PEERS
    type: mpls
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '6.6971'
  address_family_ipv4:
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: false
  address_family_evpn:
    neighbor_default:
      encapsulation: mpls
      next_hop_self_source_interface: Loopback0
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv4:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: null
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv6:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: null
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  neighbors:
  - ip_address: 100.1.1.1
    peer_group: MPLS-OVERLAY-PEERS
    description: SF_SITE_101_RR-1
  - ip_address: 100.1.1.2
    peer_group: MPLS-OVERLAY-PEERS
    description: SF_SITE_102_RR-1
  vrfs:
  - name: BRANCH-10013
    router_id: 100.1.2.2
    rd: 100.1.2.2:10013
    route_targets:
      import:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10013
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10013
      export:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10013
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10013
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      neighbors:
      - ip_address: 10.255.101.3
        activate: true
      bgp:
        additional_paths:
          install: true
    neighbors:
    - ip_address: 10.255.101.3
      remote_as: '65503'
      bfd: true
    eos_cli: 'bgp additional-paths receive

      bgp additional-paths send any

      bgp bestpath tie-break router-id

      '
  - name: CORP-10014
    router_id: 100.1.2.2
    rd: 100.1.2.2:10014
    route_targets:
      import:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10014
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10014
      export:
      - address_family: vpn-ipv4
        route_targets:
        - 6.6971:10014
      - address_family: vpn-ipv6
        route_targets:
        - 6.6971:10014
    redistribute_routes:
    - source_protocol: connected
    address_family_ipv4:
      neighbors:
      - ip_address: 10.255.101.3
        activate: true
      bgp:
        additional_paths:
          install: true
    neighbors:
    - ip_address: 10.255.101.3
      remote_as: '65504'
      bfd: true
    eos_cli: 'bgp additional-paths receive

      bgp additional-paths send any

      bgp bestpath tie-break router-id

      '
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: default
- ip_address: 8.8.4.4
  vrf: default
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$ZSpmKHG8tfWO/BQg$qMy2VGDhmykJ.VDcO5LiW9B6pf0TS7zVe4jLwaCiIjxNwBEOXodwhsIwFUD3UuLAR.aDtVZh3DIuSr5X12dmB0
vrfs:
- name: default
  ip_routing: false
- name: BRANCH-10013
  tenant: BRANCH
  ip_routing: true
- name: CORP-10014
  tenant: CORP
  ip_routing: true
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.15/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
eos_cli: "!\nmpls label range bgp-sr 16000 8000\nmpls label range isis-sr 16000 8000\nmpls label range static 16 15984\n!\nrouter bgp
  6.6971\n  vpws BRANCH\n    mpls control-word\n  address-family vpn-ipv4\n    bgp additional-paths receive\n    bgp additional-paths
  send any\n  address-family vpn-ipv6\n    bgp additional-paths receive\n    bgp additional-paths send any\n!\nqos map exp 0 to traffic-class
  0\nqos map exp 1 to traffic-class 1\n!\npolicy-map type quality-of-service TENANT-INGRESS-CLASSIFIER-1G\n class BUSINESS\n    police
  rate 1440 mbps burst-size 125000 bytes rate 1540 mbps burst-size 125000 bytes\n"
ethernet_interfaces:
- name: Ethernet11
  peer: SF_SITE_101_TOR-1B
  peer_interface: Ethernet3
  peer_type: ethernet_aggregation
  description: SF_SITE_101_TOR-1B_Ethernet3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 11
    mode: active
- name: Ethernet12
  peer: SF_SITE_101_TOR-1B
  peer_interface: Ethernet4
  peer_type: ethernet_aggregation
  description: SF_SITE_101_TOR-1B_Ethernet4
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 11
    mode: active
- name: Ethernet3
  peer: SF_SITE_101_SPINE-1
  peer_interface: Ethernet4
  peer_type: p
  description: P2P_LINK_TO_SF_SITE_101_SPINE-1_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.0.0.3/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet4
  peer: SF_SITE_101_SPINE-2
  peer_interface: Ethernet4
  peer_type: p
  description: P2P_LINK_TO_SF_SITE_101_SPINE-2_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.0.0.7/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet7
  peer: SF_SITE_101_RR-1
  peer_interface: Ethernet4
  peer_type: rr
  description: P2P_LINK_TO_SF_SITE_101_RR-1_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.0.0.10/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet9
  peer: SF_SITE_103_BL-1
  peer_interface: Ethernet9
  peer_type: pe
  description: P2P_LINK_TO_SF_SITE_103_BL-1_Ethernet9
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.4/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Port-channel11.101
  peer_type: l3_interface
  ip_address: 10.255.101.2/31
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 101
  vrf: BRANCH-10013
  service_policy:
    qos:
      input: TENANT-INGRESS-CLASSIFIER-1G
- name: Port-channel11.201
  peer_type: l3_interface
  ip_address: 10.255.101.6/31
  shutdown: false
  type: l3dot1q
  encapsulation_dot1q_vlan: 201
  vrf: CORP-10014
  service_policy:
    qos:
      input: TENANT-INGRESS-CLASSIFIER-1G
- name: Port-channel11
  type: routed
  peer_type: l3_interface
  shutdown: false
port_channel_interfaces:
- name: Port-Channel11
  description: SF_SITE_101_TOR-1B_Po3
  type: switched
  shutdown: false
  mode: trunk
  vlans: 100-101,200-201
  service_policy:
    qos:
      input: TENANT-INGRESS-CLASSIFIER-1G
loopback_interfaces:
- name: Loopback0
  description: MPLS_Overlay_peering
  shutdown: false
  ip_address: 100.1.2.2/32
  isis_enable: CORE
  isis_passive: true
  node_segment:
    ipv4_index: 2
- name: Loopback10
  description: Inband management
  ip_address: 192.168.101.15/32
router_isis:
  instance: CORE
  log_adjacency_changes: true
  net: null
  router_id: 100.1.2.2
  is_type: level-2
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
  advertise:
    passive_only: false
  segment_routing_mpls:
    router_id: 100.1.2.2
    enabled: true
mpls:
  ip: true
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
vlans:
- id: 100
  name: vlan_100
  tenant: BRANCH
- id: 101
  name: vlan_101
  tenant: BRANCH
- id: 200
  name: vlan_200
  tenant: CORP
- id: 201
  name: vlan_201
  tenant: CORP
ip_igmp_snooping:
  globally_enabled: true
logging:
  console: critical
  monitor: disabled
  buffered:
    size: 180000
    level: informational
  trap: warnings
  synchronous:
    level: critical
  format:
    timestamp: high-resolution
    sequence_numbers: true
  source_interface: Loopback10
  policy:
    match:
      match_lists:
      - name: SAKlogs
        action: discard
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
