hostname: SF_SITE_103_TOR-1A
service_routing_protocols_model: multi-agent
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: default
- ip_address: 8.8.4.4
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 32768
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$ZSpmKHG8tfWO/BQg$qMy2VGDhmykJ.VDcO5LiW9B6pf0TS7zVe4jLwaCiIjxNwBEOXodwhsIwFUD3UuLAR.aDtVZh3DIuSr5X12dmB0
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.26/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
ethernet_interfaces:
- name: Ethernet3
  peer: SF_SITE_103_BL-1
  peer_interface: Ethernet3
  peer_type: pe
  description: SF_SITE_103_BL-1_Ethernet3
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 3
    mode: active
- name: Ethernet4
  peer: SF_SITE_103_BL-1
  peer_interface: Ethernet4
  peer_type: pe
  description: SF_SITE_103_BL-1_Ethernet4
  shutdown: false
  type: port-channel-member
  channel_group:
    id: 3
    mode: active
port_channel_interfaces:
- name: Port-Channel3
  description: SF_SITE_103_BL-1_Po3
  type: switched
  shutdown: false
  mode: trunk
  vlans: none
ip_igmp_snooping:
  globally_enabled: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
