hostname: SF_SITE_102_BL-2
router_bgp:
  as: '6.6971'
  router_id: 100.2.2.2
  distance:
    external_routes: 20
    internal_routes: 200
    local_routes: 200
  bgp_defaults:
  - bgp asn notation asdot
  - bgp always-compare-med
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  graceful_restart:
    enabled: true
    restart_time: 300
  peer_groups:
  - name: MPLS-OVERLAY-PEERS
    type: mpls
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '6.6971'
  address_family_ipv4:
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: false
  address_family_evpn:
    neighbor_default:
      encapsulation: mpls
      next_hop_self_source_interface: Loopback0
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv4:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: null
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  address_family_vpn_ipv6:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: Loopback0
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
  neighbors:
  - ip_address: 100.1.1.1
    peer_group: MPLS-OVERLAY-PEERS
    description: SF_SITE_101_RR-1
  - ip_address: 100.1.1.2
    peer_group: MPLS-OVERLAY-PEERS
    description: SF_SITE_102_RR-1
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
ip_name_servers:
- ip_address: 8.8.8.8
  vrf: default
- ip_address: 8.8.4.4
  vrf: default
local_users:
- name: cvpadmin
  privilege: 15
  role: network-admin
  sha512_password: $6$ZSpmKHG8tfWO/BQg$qMy2VGDhmykJ.VDcO5LiW9B6pf0TS7zVe4jLwaCiIjxNwBEOXodwhsIwFUD3UuLAR.aDtVZh3DIuSr5X12dmB0
vrfs:
- name: default
  ip_routing: false
management_interfaces:
- name: Management1
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.22/24
  gateway: null
  type: oob
management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: MPLS_Overlay_peering
  shutdown: false
  ip_address: 100.2.2.2/32
  isis_enable: CORE
  isis_passive: true
  node_segment:
    ipv4_index: 2
router_isis:
  instance: CORE
  log_adjacency_changes: true
  net: null
  router_id: 100.2.2.2
  is_type: level-2
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
  advertise:
    passive_only: false
  segment_routing_mpls:
    router_id: 100.2.2.2
    enabled: true
mpls:
  ip: true
router_bfd:
  multihop:
    interval: 1200
    min_rx: 1200
    multiplier: 3
ethernet_interfaces:
- name: Ethernet3
  peer: SF_SITE_102_SPINE-1
  peer_interface: Ethernet4
  peer_type: p
  description: P2P_LINK_TO_SF_SITE_102_SPINE-1_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.3/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet4
  peer: SF_SITE_102_SPINE-2
  peer_interface: Ethernet4
  peer_type: p
  description: P2P_LINK_TO_SF_SITE_102_SPINE-2_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.7/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet7
  peer: SF_SITE_102_RR-1
  peer_interface: Ethernet4
  peer_type: rr
  description: P2P_LINK_TO_SF_SITE_102_RR-1_Ethernet4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.10/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
- name: Ethernet10
  peer: SF_SITE_103_BL-1
  peer_interface: Ethernet10
  peer_type: pe
  description: P2P_LINK_TO_SF_SITE_103_BL-1_Ethernet10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.0.8/31
  isis_enable: CORE
  isis_metric: 50
  isis_network_point_to_point: true
  isis_hello_padding: true
  isis_circuit_type: level-2
  mpls:
    ip: true
vlans:
- id: 100
  name: vlan_100
  tenant: BRANCH
- id: 101
  name: vlan_101
  tenant: BRANCH
ip_igmp_snooping:
  globally_enabled: true
daemon_terminattr:
  cvaddrs:
  - 192.168.0.5:9910
  cvauth:
    method: token
    token_file: /tmp/token
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
ntp:
  servers:
  - name: 0.north-america.pool.ntp.org
    preferred: true
    vrf: default
  - name: 1.north-america.pool.ntp.org
    vrf: default
