---
# BL specific configurations

PE_BGP_STRUCTURED_CONFIG:
  router_bgp:
    address_family_vpn_ipv4:
      neighbor_default_encapsulation_mpls_next_hop_self:
        source_interface: null
    address_family_vpn_ipv6:
      neighbor_default_encapsulation_mpls_next_hop_self:
        source_interface: null

PE_EOS_CLI: |
  !
  mpls label range bgp-sr 16000 8000
  mpls label range isis-sr 16000 8000
  mpls label range static 16 15984
  !
  router bgp 6.6971
    vpws BRANCH
      mpls control-word
    address-family vpn-ipv4
      bgp additional-paths receive
      bgp additional-paths send any
    address-family vpn-ipv6
      bgp additional-paths receive
      bgp additional-paths send any
  !
  qos map exp 0 to traffic-class 0
  qos map exp 1 to traffic-class 1
  !
  policy-map type quality-of-service TENANT-INGRESS-CLASSIFIER-1G
   class BUSINESS
      police rate 1440 mbps burst-size 125000 bytes rate 1540 mbps burst-size 125000 bytes