---
# BL specific configurations

PE_BGP_STRUCTURED_CONFIG:
  router_bgp:
    address_family_vpn_ipv4:
      neighbor_default_encapsulation_mpls_next_hop_self:
        source_interface: null
    address_family_vpn_ipv6:
      neighbor_default_encapsulation_mpls_next_hop_self:
        source_interface: null

PE_EOS_CLI: |
  !
  mpls label range static 16 15984
  mpls label range bgp-sr 16000 8000
  mpls label range isis-sr 16000 8000
  
  !
  router bgp 6.6971
    vpws BRANCH
      mpls control-word
    address-family vpn-ipv4
      bgp additional-paths receive
      bgp additional-paths send any
    address-family vpn-ipv6
      bgp additional-paths receive
      bgp additional-paths send any
  
  !
  router isis CORE
    lsp purge origination-identification
    set-overload-bit on-startup wait-for-bgp
    authentication mode md5
    graceful-restart restart-hold-time 300
    authentication key edwardjones
    address-family ipv4 unicast
      bfd all-interfaces
    address-family ipv6 unicast
      bfd all-interfaces
      multi-topology
  interface Loopback0
    isis multi-topology address-family ipv4 unicast
    isis multi-topology address-family ipv6 unicast


#fabric IS-IS routing
isis_area_id: "51.0001"
isis_default_circuit_type: level-2
isis_default_is_type: level-2
isis_default_metric: 10
#isis_maximum_paths: 4
isis_ti_lfa:
  enabled: true
  protection: node

# custom config for fabric IS-IS routing
custom_structured_configuration_router_isis:
  instance: "CORE"
  address_family_ipv4:
    enabled: true
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2
  address_family_ipv6:
    enabled: true
    fast_reroute_ti_lfa:
      mode: node-protection
      level: level-2

# MAC SECURITY PROFILE FOR WAN LINKS
# custom_structured_configuration_mac_security:
#   fips_restrictions: true
#   profiles:
#     - name: Backbone
#       cipher:  aes256-gcm-xpn
#       connection_keys:
#         - id: 4261636b62306e65
#           encrypted_key: 08751E18584F5641105D5E577A7D217E6661204054415A
#           # fallback: true
#       mka:
#         session:
#           rekey_period: 86400
