---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.x.x
    AVD_FABRIC:
      children:
        SF_SITE_104:
          children:
            BORDER_LEAFS_104:
              hosts:
                SF_SITE_104_BL-1:
                  ansible_host: 10.255.x.x
