---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.x.x
    AVD_FABRIC:
      children:
        SF_SITE_101:
          children:
            SPINES_101:
              hosts:
                SF_SITE_101_SPINE-1:
                  ansible_host: 10.255.x.x
                SF_SITE_101_SPINE-2:
                  ansible_host: 10.255.x.x
            BORDER_LEAFS_101:
              hosts:
                SF_SITE_101_BL-1:
                  ansible_host: 10.255.x.x
                SF_SITE_101_BL-2:
                  ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_101:
              hosts:
                SF_SITE_101_RR-1:
                  ansible_host: 10.255.x.x
            TOR_101:
              hosts:
                SF_SITE_101_TOR-1A:
                  ansible_host: 10.255.x.x
                SF_SITE_101_TOR-1B:
                  ansible_host: 10.255.x.x
