---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.x.x
    AVD_FABRIC:
      children:
        SF_SITE_102:
          children:
            SPINES_102:
              hosts:
                SF_SITE_102_SPINE-1:
                  ansible_host: 10.255.x.x
                SF_SITE_102_SPINE-2:
                  ansible_host: 10.255.x.x
            BORDER_LEAFS_102:
              hosts:
                SF_SITE_102_BL-1:
                  ansible_host: 10.255.x.x
                SF_SITE_102_BL-2:
                  ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_102:
              hosts:
                SF_SITE_102_RR-1:
                  ansible_host: 10.255.x.x
            TOR_SITE_102:
              hosts:
                SF_SITE_102_TOR-1A:
                  ansible_host: 10.255.x.x
                SF_SITE_102_TOR-1B:
                  ansible_host: 10.255.x.x
