---
# Simulation of customer edge devices

type: ce

ce:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
  nodes:
    - name: BRANCH-A2A-CE3
      id: 32
      mgmt_ip: 192.168.0.32/24
    - name: BRANCH-A2A-CE4
      id: 33
      mgmt_ip: 192.168.0.33/24
    - name: CORP-A2A-CE3
      id: 34
      mgmt_ip: 192.168.0.34/24
    - name: CORP-A2A-CE4
      id: 35
      mgmt_ip: 192.168.0.35/24
    - name: BRANCH-VPWS-CE2
      id: 41
      mgmt_ip: 192.168.0.41/24
    - name: BRANCH-HS-CE2
      id: 43
      mgmt_ip: 192.168.0.43/24
# DOES NOT PROVIDE THE INTENDED OUTCOME. IP ROUTING IS NOT CONFIGURED ON ROUTER
vrfs:
  - name: default
    ip_routing: true
# IP ROUTING CONFIGURATION
custom_structured_configuration_ip_routing: true
