---
# Simulation of customer edge devices

type: ce

ce:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
  nodes:
    - name: BRANCH-A2A-CE5
      id: 36
      mgmt_ip: 192.168.0.36/24
    - name: CORP-A2A-CE5
      id: 37
      mgmt_ip: 192.168.0.37/24
    - name: BRANCH-HS-CE3
      id: 44
      mgmt_ip: 192.168.0.44/24

# DOES NOT PROVIDE THE INTENDED OUTCOME. IP ROUTING IS NOT CONFIGURED ON ROUTER
vrfs:
  - name: default
    ip_routing: true
# IP ROUTING CONFIGURATION
custom_structured_configuration_ip_routing: true
