---
# Simulation of customer edge devices

type: ce

ce:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp
  nodes:
    - name: BRANCH-A2A-CE5
      id: 1
      mgmt_ip: 192.168.0.36/24
    - name: CORP-A2A-CE5
      id: 3
      mgmt_ip: 192.168.0.37/24

vrfs:
  - name: default
    ip_routing: true
