---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.x.x
    AVD_FABRIC:
      children:
        SF_SITE_101:
          children:
            SPINES_101:
              hosts:
                SF_SITE_101_SPINE-1:
                  ansible_host: 10.255.x.x
                SF_SITE_101_SPINE-2:
                  ansible_host: 10.255.x.x
            BORDER_LEAFS_101:
              hosts:
                SF_SITE_101_BL-1:
                  ansible_host: 10.255.x.x
                SF_SITE_101_BL-2:
                  ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_101:
              hosts:
                SF_SITE_101_RR-1:
                  ansible_host: 10.255.x.x
            TOR_101:
              hosts:
                SF_SITE_101_TOR-1A:
                  ansible_host: 10.255.x.x
                SF_SITE_101_TOR-1B:
                  ansible_host: 10.255.x.x
        SF_SITE_102:
          children:
        #     SPINES_102:
        #       hosts:
        #         SF_SITE_102_SPINE-1:
        #           ansible_host: 10.255.x.x
        #         SF_SITE_102_SPINE-2:
        #           ansible_host: 10.255.x.x
        #     BORDER_LEAFS_102:
        #       hosts:
        #         SF_SITE_102_BL-1:
        #           ansible_host: 10.255.x.x
        #         SF_SITE_102_BL-2:
        #           ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_102:
              hosts:
                SF_SITE_102_RR-1:
                  ansible_host: 10.255.x.x
        #     TOR_SITE_102:
        #       hosts:
        #         SF_SITE_102_TOR-1A:
        #           ansible_host: 10.255.x.x
        #         SF_SITE_102_TOR-1B:
        #           ansible_host: 10.255.x.x
        # SF_SITE_103:
        #   children:
        #     BORDER_LEAFS_103:
        #       hosts:
        #         SF_SITE_103_BL-1:
        #           ansible_host: 10.255.x.x
        #     TOR_SITE_103:
        #       hosts:
        #         SF_SITE_102_TOR-1A:
        #           ansible_host: 10.255.x.x
        SF_SITE_104:
          children:
            BORDER_LEAFS_104:
              hosts:
                SF_SITE_104_BL-1:
                  ansible_host: 10.255.x.x
    ROUTE_REFLECTORS:
      children:
        ROUTE_REFLECTORS_101:
        ROUTE_REFLECTORS_102: