---
all:
  children:
    CVP:
      hosts:
        ACT_CVP:
          ansible_host: 10.255.60.69
          ansible_httpapi_host: 10.225.60.69
          ansible_user: cvpadmin
          ansible_password: edwardjones
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: true
          ansible_httpapi_validate_certs: false
          ansible_network_os: eos
          ansible_httpapi_port: 443
          # Configuration to get Virtual Env information
          ansible_python_interpreter: $(which python3)
    AVD_FABRIC:
      children:
        SF_SITE_101:
          children:
            SPINES_101:
              hosts:
                SF-SITE-101-SPINE-1:
                  ansible_host: 10.255.x.x
                SF-SITE-101-SPINE-2:
                  ansible_host: 10.255.x.x
            BORDER_LEAFS_101:
              hosts:
                SF-SITE-101-BL-1:
                  ansible_host: 10.255.x.x
                SF-SITE-101-BL-2:
                  ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_101:
              hosts:
                SF-SITE-101-RR-1:
                  ansible_host: 10.255.x.x
            TOR_101:
              hosts:
                SF-SITE-101-TOR-1A:
                  ansible_host: 10.255.x.x
                SF-SITE-101-TOR-1B:
                  ansible_host: 10.255.x.x
            # Customer edge (host simulation)
            CE_101:
              hosts:
                BRANCH-A2A-CE1:
                  ansible_host: 10.255.x.x
                  #is_deployed: false
                BRANCH-A2A-CE2:
                  ansible_host: 10.255.x.x
                BRANCH-VPWS-CE1:
                  ansible_host: 10.225.x.x
                BRANCH-HS-CE1:
                  ansible_host: 10.255.x.x
                  #is_deployed: false
                CORP-A2A-CE1:
                  ansible_host: 10.255.x.x
                CORP-A2A-CE2:
                  ansible_host: 10.255.x.x
        SF_SITE_102:
          children:
            SPINES_102:
              hosts:
                SF-SITE-102-SPINE-1:
                  ansible_host: 10.255.x.x
                SF-SITE-102-SPINE-2:
                  ansible_host: 10.255.x.x
            BORDER_LEAFS_102:
              hosts:
                SF-SITE-102-BL-1:
                  ansible_host: 10.255.x.x
                SF-SITE-102-BL-2:
                  ansible_host: 10.255.x.x
            ROUTE_REFLECTORS_102:
              hosts:
                SF-SITE-102-RR-1:
                  ansible_host: 10.255.x.x
            TOR_102:
              hosts:
                SF-SITE-102-TOR-1A:
                  ansible_host: 10.255.x.x
                SF-SITE-102-TOR-1B:
                  ansible_host: 10.255.x.x
            # Customer edge (host simulation)
            CE_102:
              hosts:
                BRANCH-A2A-CE3:
                  ansible_host: 10.255.x.x
                BRANCH-A2A-CE4:
                  ansible_host: 10.255.x.x
                BRANCH-VPWS-CE2:
                  ansible_host: 10.255.x.x
                BRANCH-HS-CE2:
                  ansible_host: 10.255.x.x
                  #is_deployed: false
                CORP-A2A-CE3:
                  ansible_host: 10.255.x.x
                CORP-A2A-CE4:
                  ansible_host: 10.255.x.x
                
        SF_SITE_103:
          children:
            BORDER_LEAFS_103:
              hosts:
                SF-SITE-103-BL-1:
                  ansible_host: 10.255.x.x
            TOR_103:
              hosts:
                SF-SITE-103-TOR-1A:
                  ansible_host: 10.255.x.x
            CE_103:
              hosts:
                BRANCH-A2A-CE5:
                  ansible_host: 10.255.x.x
                BRANCH-HS-CE3:
                  ansible_host: 10.255.x.x
                  #is_deployed: false
                CORP-A2A-CE5:
                  ansible_host: 10.255.x.x
                
        SF_SITE_104:
          children:
            BORDER_LEAFS_104:
              hosts:
                SF-SITE-104-BL-1:
                  ansible_host: 10.255.x.x
            CE_104:
              hosts:
                BRANCH-A2A-CE6:
                  ansible_host: 10.255.x.x
                CORP-A2A-CE6:
                  ansible_host: 10.255.x.x
    ROUTE_REFLECTORS:
      children:
        ROUTE_REFLECTORS_101:
        ROUTE_REFLECTORS_102:
    SPINES:
      children:
        SPINES_101:
        SPINES_102:
    TENANT_NETWORKS:
      children:
        BORDER_LEAFS_101:
        BORDER_LEAFS_102:
        BORDER_LEAFS_103:
        BORDER_LEAFS_104:
        TOR_101:
        TOR_102:
        TOR_103:
    ALL_BL:
      children:
        BORDER_LEAFS_101:
        BORDER_LEAFS_102:
        BORDER_LEAFS_103:
        BORDER_LEAFS_104:
