---
# RR ISIS specific configurations

PE_EOS_CLI: |
  !
  router isis CORE
    lsp purge origination-identification
    set-overload-bit on-startup wait-for-bgp
    authentication mode md5
    graceful-restart restart-hold-time 300
    authentication key 7 U93fJqF1/pY=
    address-family ipv4 unicast
      bfd all-interfaces
  !
  interface Loopback10
    isis multi-topology address-family ipv4 unicast
    isis multi-topology address-family ipv6 unicast


